[window]
# This section documents the [window] table of the configuration file.

dimensions = { columns = 100, lines = 30 }

# Window dimensions (changes require restart).

# Number of lines/columns (not pixels) in the terminal. Both lines and columns must be non-zero for this to take effect    . The number of columns must be at least 2, while using a value of 0 for columns and lines will fall back to the window     manager's recommended size

decorations = "None" 

# Window decorations.

# *Full*
# 	Borders and title bar.
# *None*
# 	Neither borders nor title bar.
# *Transparent* _(macOS only)_
# 	Title bar, transparent background and title bar buttons.
# *Buttonless* _(macOS only)_
# 	Title bar, transparent background and no title bar buttons.
# 
# Default: _"Full"_ 
opacity = 0.6

blur = true

option_as_alt = "OnlyLeft"

startup_mode = "Maximized"


# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'
